version: '3.1'
services:

  main-server:
    build: .
    container_name: main-server-container
    ports:
      - "8080:8080"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - main-db
      - pictures-db

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/hahaton
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  main-db:
    image: postgres:14-alpine
    container_name: main-db-container
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - POSTGRES_DB=hahaton
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pictures-db:
    image: mongo
    container_name: mongo-db-container
    environment:
      - MONGO_INITDB_DATABASE=pictures
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb


